### ISSUE TITLE
Suggestion: UBO for search engine results

### ISSUE THREAD

**Issue by nicoleahmed** [KisaragiEffective/PortableFormatOfIllegalModSites#2]
Hi
This is a great project!

The UBL and UBO lists are very useful

I am not sure if your UBO sites in their current format also block  results from search engines the way UBL does.

There is a way to do it.
For example:
UBL-             *://*.1r1g.cn/*
becomes
UBO              www.google.*##.g:has(a[href*="1r1g.cn"])

See here for more information and different search engines:
https://letsblock.it/filters/search-results

This is useful where people can't install UBL (e.g. some mobiles devices)

**Comment by KisaragiEffective** [comment]
Hi, thanks for suggestion!

This list does not block search engine entries, because I've modified a bit to make them conform to both UBL and UBO.

However, it would be worth doing. This suggestion requires changing build systems, so stay tuned!

**Comment by nicoleahmed** [comment]
Great 
I think both ubo lists would be of value

I've been toying with the idea of converting my ubl lists to both  

Ubo general filters  
Ubo search engine filters  

Will keep watching!

**Comment by KisaragiEffective** [comment]
implemented in #8, you can find it from https://github.com/KisaragiEffective/PortableFormatOfIllegalModSites/blob/master/dist/minecraft/ublockorigin_google.txt
